[package]
name = "wasmer/wabt"
version = "1.0.36"
description = "The WebAssembly Binary Toolkit"
readme = "README-wapm.md"
repository = "https://github.com/wapm-packages/wabt"

[[module]]
name = "wabt"
source = "out/libwabt.wasm"
abi = "wasi"
interfaces = { wasi = "0.1.0-unstable" }
bindings = { wit-exports = "src/embedding/wabt.wai", wit-bindgen = "0.1.0" }

[[module]]
name = "wat2wasm"
source = "out/wat2wasm.wasm"
abi = "wasi"
interfaces = { wasi = "0.1.0-unstable" }

[[module]]
name = "wast2json"
source = "out/wast2json.wasm"
abi = "wasi"
interfaces = { wasi = "0.1.0-unstable" }

[[module]]
name = "wasm2wat"
source = "out/wasm2wat.wasm"
abi = "wasi"
interfaces = { wasi = "0.1.0-unstable" }

[[module]]
name = "wasm-interp"
source = "out/wasm-interp.wasm"
abi = "wasi"
interfaces = { wasi = "0.1.0-unstable" }

[[module]]
name = "wasm-validate"
source = "out/wasm-validate.wasm"
abi = "wasi"
interfaces = { wasi = "0.1.0-unstable" }

[[module]]
name = "wasm-strip"
source = "out/wasm-strip.wasm"
abi = "wasi"
interfaces = { wasi = "0.1.0-unstable" }

# The commands for each module
[[command]]
name = "wat2wasm"
module = "wat2wasm"

[[command]]
name = "wast2json"
module = "wast2json"

[[command]]
name = "wasm2wat"
module = "wasm2wat"

[[command]]
name = "wasm-interp"
module = "wasm-interp"

[[command]]
name = "wasm-validate"
module = "wasm-validate"

[[command]]
name = "wasm-strip"
module = "wasm-strip"
